# Generated by Django 4.1 on 2022-08-23 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_inicial', '0002_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='body',
            old_name='texto',
            new_name='texto_body',
        ),
        migrations.RenameField(
            model_name='body',
            old_name='titulo',
            new_name='titulo_body',
        ),
    ]
