# Generated by Django 4.1 on 2022-08-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_inicial', '0004_body_subtitulo_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotosBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_foto_body', models.CharField(max_length=100)),
                ('foto_body', models.ImageField(blank=True, upload_to='static/foto_body')),
            ],
        ),
    ]
