# Generated by Django 4.1 on 2022-08-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_inicial', '0005_fotosbody'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendeBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_agende', models.CharField(max_length=100)),
                ('foto_agende', models.ImageField(blank=True, upload_to='static/agende')),
                ('link_agende', models.CharField(max_length=500)),
            ],
        ),
    ]
